function b = b_pend(in1,in2,in3)
%B_PEND
%    B = B_PEND(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    30-Oct-2021 03:10:45

c1 = in3(:,1);
c2 = in3(:,2);
dth1 = in1(3,:);
dth2 = in1(4,:);
g = in3(:,12);
k1 = in3(:,13);
k2 = in3(:,14);
k3 = in3(:,15);
l0 = in3(:,5);
l1 = in3(:,6);
l2 = in3(:,7);
m1 = in3(:,3);
m2 = in3(:,4);
rx = in3(:,16);
ry = in3(:,17);
tau1 = in2(1,:);
tau2 = in2(2,:);
th1 = in1(1,:);
th2 = in1(2,:);
th10 = in3(:,18);
th20 = in3(:,19);
t2 = cos(th1);
t3 = sin(th1);
t4 = sin(th2);
t5 = th1+th2;
t10 = -rx;
t6 = l1.*t2;
t7 = cos(t5);
t8 = l1.*t3;
t9 = sin(t5);
t11 = l2.*t7;
t12 = l2.*t9;
t13 = ry+t6+t11;
t15 = t8+t10+t12;
t14 = t13.^2;
t16 = t15.^2;
t17 = t14+t16;
t18 = sqrt(t17);
t19 = 1.0./t18;
t20 = -t18;
t21 = l0+t20;
b = [tau1-k1.*(th1-th10)-g.*m2.*(t8+c2.*t9)-c1.*g.*m1.*t3-(k3.*t19.*t21.*(rx.*t6.*2.0+rx.*t11.*2.0+ry.*t8.*2.0+ry.*t12.*2.0))./2.0+c2.*dth2.*l1.*m2.*t4.*(dth1.*2.0+dth2);tau2-k2.*(th2-th20)-c2.*g.*m2.*t9-k3.*l2.*t19.*t21.*(l1.*t4+rx.*t7+ry.*t9)-c2.*dth1.*l1.*m2.*t4.*(dth1+dth2)+c2.*dth1.*dth2.*l1.*m2.*t4];
