function E = energy_pend(in1,in2)
%ENERGY_PEND
%    E = ENERGY_PEND(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    30-Oct-2021 03:10:46

c1 = in2(:,1);
c2 = in2(:,2);
dth1 = in1(3,:);
dth2 = in1(4,:);
g = in2(:,12);
i1 = in2(:,8);
i2 = in2(:,9);
k1 = in2(:,13);
k2 = in2(:,14);
k3 = in2(:,15);
l0 = in2(:,5);
l1 = in2(:,6);
l2 = in2(:,7);
m1 = in2(:,3);
m2 = in2(:,4);
rx = in2(:,16);
ry = in2(:,17);
th1 = in1(1,:);
th2 = in1(2,:);
th10 = in2(:,18);
th20 = in2(:,19);
t2 = cos(th1);
t3 = sin(th1);
t4 = th1+th2;
t5 = c1.^2;
t6 = dth1.^2;
t7 = l1.*t2;
t8 = cos(t4);
t9 = l1.*t3;
t10 = sin(t4);
t11 = c2.*t8;
t12 = t7+t11;
E = (i1.*t6)./2.0+(m1.*(t2.^2.*t5.*t6+t3.^2.*t5.*t6))./2.0+(m2.*((dth1.*(t9+c2.*t10)+c2.*dth2.*t10).^2+(dth1.*t12+dth2.*t11).^2))./2.0+(dth2.^2.*i2)./2.0+(k1.*(th1-th10).^2)./2.0+(k2.*(th2-th20).^2)./2.0+(k3.*(l0-sqrt(abs(ry+t7+l2.*t8).^2+abs(-rx+t9+l2.*t10).^2)).^2)./2.0-g.*m2.*t12-c1.*g.*m1.*t2;
