function rB = point_b(in1,in2)
%POINT_B
%    RB = POINT_B(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    30-Oct-2021 03:10:45

l1 = in2(:,6);
th1 = in1(1,:);
rB = [l1.*sin(th1);-l1.*cos(th1)];
