function A = A_pend(in1,in2)
%A_PEND
%    A = A_PEND(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    30-Oct-2021 03:03:50

c1 = in2(:,1);
c2 = in2(:,2);
i1 = in2(:,7);
i2 = in2(:,8);
l1 = in2(:,5);
m1 = in2(:,3);
m2 = in2(:,4);
th2 = in1(2,:);
t2 = cos(th2);
t3 = c2.^2;
t4 = l1.*t2;
t5 = m2.*t3;
t6 = c2+t4;
t7 = c2.*m2.*t6;
A = reshape([i1+t5+c1.^2.*m1+l1.^2.*m2+c2.*m2.*t4.*2.0,t7,t7,i2+t5],[2,2]);
