function b = b_pend(in1,in2,in3)
%B_PEND
%    B = B_PEND(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    30-Oct-2021 03:03:50

c1 = in3(:,1);
c2 = in3(:,2);
dth1 = in1(3,:);
dth2 = in1(4,:);
g = in3(:,9);
l1 = in3(:,5);
m1 = in3(:,3);
m2 = in3(:,4);
tau1 = in2(1,:);
tau2 = in2(2,:);
th1 = in1(1,:);
th2 = in1(2,:);
t2 = sin(th1);
t3 = sin(th2);
t4 = th1+th2;
t5 = sin(t4);
t6 = c2.*g.*m2.*t5;
t7 = -t6;
b = [t7+tau1-c1.*g.*m1.*t2-g.*l1.*m2.*t2+c2.*dth2.^2.*l1.*m2.*t3+c2.*dth1.*dth2.*l1.*m2.*t3.*2.0;t7+tau2-c2.*dth1.^2.*l1.*m2.*t3];
