function keypoints = key_pend(in1,in2)
%KEY_PEND
%    KEYPOINTS = KEY_PEND(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    30-Oct-2021 01:59:29

l = in2(:,3);
th = in1(1,:);
keypoints = [l.*sin(th);-l.*cos(th)];
