function A = A_pend(in1,in2)
%A_PEND
%    A = A_PEND(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    12-Nov-2021 15:07:42

I1 = in2(6,:);
I2 = in2(8,:);
c1 = in2(1,:);
c2 = in2(3,:);
l1 = in2(2,:);
m1 = in2(5,:);
m2 = in2(7,:);
th2 = in1(2,:);
t2 = cos(th2);
t3 = c2.^2;
t4 = c2.*m2.*2.0;
t5 = c1.*m1.*t2;
t6 = m2.*t3;
t7 = l1.*m2.*t2.*2.0;
t8 = t4+t5+t7;
t9 = (c2.*t8)./2.0;
A = reshape([I1+t6+c2.*t5+l1.^2.*m2+c1.*l1.*m1+l1.*t2.*t4,t9,t9,I2+t6],[2,2]);
