function coriolis = coriolis_pend(in1,in2)
%CORIOLIS_PEND
%    CORIOLIS = CORIOLIS_PEND(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    12-Nov-2021 15:07:43

c1 = in2(1,:);
c2 = in2(3,:);
dth1 = in1(3,:);
dth2 = in1(4,:);
l1 = in2(2,:);
m1 = in2(5,:);
m2 = in2(7,:);
th2 = in1(2,:);
t2 = sin(th2);
t3 = c1.*m1;
t4 = l1.*m2.*2.0;
t5 = t3+t4;
coriolis = [c2.*dth2.*t2.*t5.*(dth1.*2.0+dth2).*(-1.0./2.0);(c2.*dth1.^2.*t2.*t5)./2.0];
