function rC = end_pend(in1,in2)
%END_PEND
%    RC = END_PEND(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    11-Nov-2021 15:30:54

l1 = in2(:,5);
l2 = in2(:,6);
th1 = in1(1,:);
th2 = in1(2,:);
t2 = th1+th2;
rC = [l2.*sin(t2)+l1.*sin(th1);-l2.*cos(t2)-l1.*cos(th1)];
