function E = energy_pend(in1,in2)
%ENERGY_PEND
%    E = ENERGY_PEND(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    11-Nov-2021 15:30:54

c1 = in2(:,1);
c2 = in2(:,2);
dth1 = in1(3,:);
dth2 = in1(4,:);
g = in2(:,9);
i1 = in2(:,7);
i2 = in2(:,8);
l1 = in2(:,5);
m1 = in2(:,3);
m2 = in2(:,4);
th1 = in1(1,:);
th2 = in1(2,:);
t2 = cos(th1);
t3 = sin(th1);
t4 = th1+th2;
t5 = c1.^2;
t6 = dth1.^2;
t7 = l1.*t2;
t8 = cos(t4);
t9 = sin(t4);
t10 = c2.*t8;
t11 = t7+t10;
E = (i1.*t6)./2.0+(m2.*((dth1.*t11+dth2.*t10).^2+(dth1.*(c2.*t9+l1.*t3)+c2.*dth2.*t9).^2))./2.0+(m1.*(t2.^2.*t5.*t6+t3.^2.*t5.*t6))./2.0+(dth2.^2.*i2)./2.0-g.*m2.*t11-c1.*g.*m1.*t2;
