function J_B_dot = Jdot_rB(in1,in2)
%JDOT_RB
%    J_B_DOT = JDOT_RB(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    12-Nov-2021 15:07:43

dth1 = in1(3,:);
dth2 = in1(4,:);
l1 = in2(2,:);
l2 = in2(4,:);
th1 = in1(1,:);
th2 = in1(2,:);
t2 = th1+th2;
t3 = cos(t2);
t4 = sin(t2);
t5 = dth2.*l2.*t3;
t6 = dth2.*l2.*t4;
t7 = -t6;
J_B_dot = reshape([t7-dth1.*(l2.*t4+l1.*sin(th1)),t5+dth1.*(l2.*t3+l1.*cos(th1)),t7-dth1.*l2.*t4,t5+dth1.*l2.*t3],[2,2]);
