function keypoints = keypoints_pend(in1,in2)
%KEYPOINTS_PEND
%    KEYPOINTS = KEYPOINTS_PEND(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    12-Nov-2021 15:07:42

l1 = in2(2,:);
l2 = in2(4,:);
th1 = in1(1,:);
th2 = in1(2,:);
t2 = cos(th1);
t3 = sin(th1);
t4 = th1+th2;
t5 = l1.*t2;
t6 = l1.*t3;
t7 = -t5;
keypoints = reshape([t6,t7,t6+l2.*sin(t4),t7-l2.*cos(t4)],[2,2]);
