function vB = velocity_rB(in1,in2)
%VELOCITY_RB
%    VB = VELOCITY_RB(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    12-Nov-2021 15:07:43

dth1 = in1(3,:);
dth2 = in1(4,:);
l1 = in2(2,:);
l2 = in2(4,:);
th1 = in1(1,:);
th2 = in1(2,:);
t2 = th1+th2;
t3 = cos(t2);
t4 = sin(t2);
vB = [dth1.*(l2.*t3+l1.*cos(th1))+dth2.*l2.*t3;dth1.*(l2.*t4+l1.*sin(th1))+dth2.*l2.*t4];
